pip install --upgradw pip
pip install aiofiles
pip install aiohttp
pip install apscheduler
pip install cairosvg
pip install cloudscraper
pip install colour
pip install covid
pip install cowpy
pip install dataclasses
pip install DateTime
pip install emoji
pip install fonttools
pip install geopy
pip install gitpython
pip install glitch_this
pip install google-api-python-client
pip install google-auth-httplib2
pip install google-auth-oauthlib
pip install gtts
pip install hachoir
pip install heroku3
pip install html-telegraph-poster
pip install httpx[http2]
pip install humanize
pip install IMDbPY
pip install jikanpy
pip install justwatch
pip install lottie
pip install lyricsgenius
pip install markdown
pip install markdown-it-py
pip install motor
pip install moviepy
pip install nekos.py
opencv-python-headless
pip install Pillow
pip install prettytable
pip install psutil
pip install psycopg2
pip install pyfiglet
pip install PyGithub
pip install pygments
pip install pylast
pip install pymediainfo
pip install PyMuPDF
pip install pySmartDL
python-barcode
pip install python-dotenv
pip install pytz
pip install qrcode
pip install randomstuff.py
pip install regex
pip install requests
pip install search-engine-parser
pip install selenium
pip install setuptools
pip install ShazamAPI
pip install spamwatch
pip install speedtest-cli
pip install sqlalchemy-json
pip install sqlalchemy==1.3.23
pip install telegraph
pip install tgcrypto
pip install ujson
pip install urlextract
pip install validators
pip install vcsi
pip install wand
pip install wget
pip install yt_dlp

pip install git+https://github.com/sandy1709/Telethon@beta
pip install git+https://github.com/goldsmith/Wikipedia
pip install git+https://github.com/sandy1709/py-googletrans
pip install git+https://github.com/alexmercerind/youtube-search-python